# Generated by Django 5.2.6 on 2025-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Termo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("termo", models.CharField(max_length=100)),
                ("definicao", models.TextField()),
            ],
        ),
    ]
