 codex/enable-django-admin-in-urls.py
# Generated by Django 5.2.6 on 2025-09-10 17:49

# Generated by Django 5.0.4 on 2025-09-10 17:47
main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Termo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
 codex/enable-django-admin-in-urls.py
                ("termo", models.CharField(max_length=100)),
                ("definicao", models.TextField()),

                ("titulo", models.CharField(max_length=200)),
                ("definicao", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
main
            ],
        ),
    ]
