# Generated by Django 5.0.4 on 2025-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Termo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("definicao", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
