# Generated by Django 5.2.6 on 2025-09-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossario", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="termo",
            old_name="descricao",
            new_name="explicacao",
        ),
        migrations.AddField(
            model_name="termo",
            name="decod_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Decodificação em inglês"
            ),
        ),
        migrations.AddField(
            model_name="termo",
            name="decod_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Decodificação em português"
            ),
        ),
        migrations.AddField(
            model_name="termo",
            name="fotos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="termo",
            name="links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="termo",
            name="videos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="termo",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="Sigla ou palavra"),
        ),
    ]
