# Generated by Django 5.2.6 on 2025-09-10 20:52

import django.db.models.deletion
import glossario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0002_rename_descricao_termo_explicacao_termo_decod_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termo',
            name='fotos',
        ),
        migrations.RemoveField(
            model_name='termo',
            name='links',
        ),
        migrations.RemoveField(
            model_name='termo',
            name='videos',
        ),
        migrations.CreateModel(
            name='TermoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=glossario.models.termo_image_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo (SEO)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título da imagem (opcional)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda (opcional)')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='glossario.termo')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TermoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('rotulo', models.CharField(blank=True, max_length=255, verbose_name='Rótulo (opcional)')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_relacionados', to='glossario.termo')),
            ],
        ),
        migrations.CreateModel(
            name='TermoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(verbose_name='URL do YouTube')),
                ('youtube_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='glossario.termo')),
            ],
        ),
    ]
