# Generated by Django 5.2.6 on 2025-09-10 21:41

import django.db.models.deletion
import glossario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0003_remove_termo_fotos_remove_termo_links_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Sigla ou palavra')),
                ('decod_en', models.CharField(blank=True, max_length=255, verbose_name='Decodificação em inglês')),
                ('decod_pt', models.CharField(blank=True, max_length=255, verbose_name='Decodificação em português')),
                ('explicacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('termo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossario.termo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=glossario.models.suggestion_image_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='glossario.suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('rotulo', models.CharField(blank=True, max_length=255)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='glossario.suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('youtube_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='glossario.suggestion')),
            ],
        ),
    ]
