# Generated by Django 5.2.6 on 2025-09-11 01:07

import django.db.models.deletion
import glossario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0004_suggestion_suggestionimage_suggestionlink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sugestão', 'verbose_name_plural': 'Sugestões'},
        ),
        migrations.AlterModelOptions(
            name='termoimage',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Imagem do termo', 'verbose_name_plural': 'Imagens do termo'},
        ),
        migrations.AlterModelOptions(
            name='termolink',
            options={'verbose_name': 'Link relacionado', 'verbose_name_plural': 'Links relacionados'},
        ),
        migrations.AddField(
            model_name='suggestion',
            name='change_type',
            field=models.CharField(choices=[('create', 'Criar novo termo'), ('complement', 'Complementar informações'), ('correction', 'Correção de informação'), ('media', 'Adicionar imagens/links/vídeos'), ('other', 'Outro')], default='complement', max_length=20, verbose_name='Tipo de sugestão'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='justification',
            field=models.TextField(blank=True, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas do administrador'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='suggestionimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo (SEO)'),
        ),
        migrations.AlterField(
            model_name='suggestionimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legenda'),
        ),
        migrations.AlterField(
            model_name='suggestionimage',
            name='imagem',
            field=models.ImageField(upload_to=glossario.models.suggestion_image_upload_to, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='suggestionimage',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='glossario.suggestion', verbose_name='Sugestão'),
        ),
        migrations.AlterField(
            model_name='suggestionimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='suggestionlink',
            name='rotulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rótulo (opcional)'),
        ),
        migrations.AlterField(
            model_name='suggestionlink',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='glossario.suggestion', verbose_name='Sugestão'),
        ),
        migrations.AlterField(
            model_name='suggestionlink',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='suggestionvideo',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='glossario.suggestion', verbose_name='Sugestão'),
        ),
        migrations.AlterField(
            model_name='suggestionvideo',
            name='youtube_id',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='ID do YouTube'),
        ),
        migrations.AlterField(
            model_name='suggestionvideo',
            name='youtube_url',
            field=models.URLField(verbose_name='URL do YouTube'),
        ),
        migrations.AlterField(
            model_name='termoimage',
            name='imagem',
            field=models.ImageField(upload_to=glossario.models.termo_image_upload_to, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='termoimage',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='termoimage',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='glossario.termo', verbose_name='Termo'),
        ),
        migrations.AlterField(
            model_name='termolink',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_relacionados', to='glossario.termo', verbose_name='Termo'),
        ),
        migrations.AlterField(
            model_name='termovideo',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='glossario.termo', verbose_name='Termo'),
        ),
        migrations.AlterField(
            model_name='termovideo',
            name='youtube_id',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='ID do YouTube'),
        ),
    ]
