# Generated by Django 5.2.6 on 2025-09-11 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0005_alter_suggestion_options_alter_termoimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fields_changed', models.JSONField(default=list)),
                ('media_added', models.IntegerField(default=0)),
                ('links_added', models.IntegerField(default=0)),
                ('videos_added', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de aplicação de sugestão',
                'verbose_name_plural': 'Logs de aplicação de sugestão',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='suggestionimage',
            constraint=models.UniqueConstraint(fields=('suggestion', 'imagem'), name='uniq_suggestion_image_path'),
        ),
        migrations.AddConstraint(
            model_name='suggestionlink',
            constraint=models.UniqueConstraint(fields=('suggestion', 'url'), name='uniq_suggestion_link_url'),
        ),
        migrations.AddConstraint(
            model_name='suggestionvideo',
            constraint=models.UniqueConstraint(fields=('suggestion', 'youtube_id'), name='uniq_suggestion_video_id'),
        ),
        migrations.AddField(
            model_name='suggestionapplicationlog',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionapplicationlog',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='glossario.suggestion'),
        ),
        migrations.AddField(
            model_name='suggestionapplicationlog',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_aplicacao', to='glossario.termo'),
        ),
    ]
