# Generated by Django 5.2.6 on 2025-09-11 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0006_suggestionapplicationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoSinonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Sinônimo/variante')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinonimos', to='glossario.termo', verbose_name='Termo')),
            ],
            options={
                'verbose_name': 'Sinônimo',
                'verbose_name_plural': 'Sinônimos',
                'unique_together': {('termo', 'nome')},
            },
        ),
    ]
