# Generated by Django 5.2.6 on 2025-09-11 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0007_termosinonimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_titulo', models.CharField(max_length=255)),
                ('previous_decod_en', models.CharField(blank=True, max_length=255)),
                ('previous_decod_pt', models.CharField(blank=True, max_length=255)),
                ('previous_explicacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='glossario.termo')),
            ],
            options={
                'verbose_name': 'Histórico de termo',
                'verbose_name_plural': 'Histórico de termos',
                'ordering': ['-created_at'],
            },
        ),
    ]
