# Generated by Django 5.2.6 on 2025-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0009_pg_trgm_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Fonte (URL)'),
        ),
    ]
