# Generated by Django 5.2.6 on 2025-09-11 18:21

import glossario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0010_suggestion_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Aerodicionário', max_length=120)),
                ('default_meta_description', models.TextField(blank=True, default='Glossário de termos e siglas da aviação para estudantes e profissionais do setor aéreo.')),
                ('default_og_image', models.ImageField(blank=True, upload_to=glossario.models.settings_upload_to)),
                ('analytics_code', models.TextField(blank=True, help_text='Cole aqui scripts de analytics (ex.: gtag).')),
                ('hero_title', models.CharField(blank=True, default='Seu guia de termos e siglas da aviação', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Da cabine de comando ao solo, descubra a linguagem que move o céu.', max_length=240)),
                ('items_per_page', models.PositiveIntegerField(default=12)),
                ('enable_autocomplete', models.BooleanField(default=True)),
                ('robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /\nSitemap: /sitemap.xml\n')),
            ],
            options={
                'verbose_name': 'Configurações do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
    ]
