# Generated by Django 5.2.6 on 2025-09-11 18:46

import glossario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0011_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='autocomplete_throttle_ms',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_js_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_js_head',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_indexing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=glossario.models.settings_upload_to),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_title_suffix',
            field=models.CharField(blank=True, default=' - Aerodicionário', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_color',
            field=models.CharField(default='#0e76e6', help_text='#RRGGBB', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_color',
            field=models.CharField(default='#065ec0', help_text='#RRGGBB', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, upload_to=glossario.models.settings_upload_to),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='suggestion_max_image_mb',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='suggestion_rate_limit_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='suggestions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='suggestions_min_justification',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='suggestions_require_source',
            field=models.BooleanField(default=True),
        ),
    ]
