# Generated by Django 5.2.6 on 2025-09-11 22:12

import glossario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0012_sitesetting_autocomplete_throttle_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_html',
            field=models.TextField(blank=True, default='<p>O Aerodicionário reúne definições claras e objetivas para estudantes, entusiastas e profissionais do setor aéreo.</p>'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(blank=True, default='Sobre o Aerodicionário', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_primary_text',
            field=models.CharField(blank=True, default='Consultar Dicionário', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_primary_url',
            field=models.URLField(blank=True, default='/dicionario/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_secondary_text',
            field=models.CharField(blank=True, default='Saiba mais', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_secondary_url',
            field=models.URLField(blank=True, default='#sobre'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='features_html',
            field=models.TextField(blank=True, default='<ul><li>Conteúdo atualizado</li><li>Busca rápida</li><li>Acesso gratuito</li></ul>'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=glossario.models.settings_upload_to),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_features',
            field=models.BooleanField(default=True),
        ),
    ]
