# Generated by Django 5.2.6 on 2025-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0013_sitesetting_about_html_sitesetting_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='faq_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='faq_title',
            field=models.CharField(blank=True, default='Perguntas frequentes', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='features_title',
            field=models.CharField(blank=True, default='Por que usar o Aerodicionário?', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='Simples, rápido e 100% gratuito.', max_length=140),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='AERODICIONÁRIO', help_text='Texto pequeno acima do título da home', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image_alt',
            field=models.CharField(blank=True, default='Imagem de destaque', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='how_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='how_title',
            field=models.CharField(blank=True, default='Como funciona', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='search_placeholder',
            field=models.CharField(blank=True, default='Buscar termos (ex.: IFR, NOTAM, APU)', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_faq',
            field=models.BooleanField(default=True, help_text='Exibir seção de FAQ'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_how',
            field=models.BooleanField(default=True, help_text="Exibir seção 'Como funciona'"),
        ),
    ]
