"""
Django settings for config project.

codex/enable-django-admin-in-urls.py
Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
main
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
codex/enable-django-admin-in-urls.py
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mmya6xp806$ro*n88r3igug^q5)7k!*sb-2q$an&+8af3y9yp3"

# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-xjd$^=y$d^z+0n^js=e52)0eoz!#@_q1cs9vt+x3wp*#3gkbcr"
 main

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
codex/enable-django-admin-in-urls.py
    'glossario',

    "glossario",
 main
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
codex/enable-django-admin-in-urls.py

                "django.template.context_processors.debug",
main
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
 codex/enable-django-admin-in-urls.py
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
 main

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
 codex/enable-django-admin-in-urls.py
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
 main

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
 codex/enable-django-admin-in-urls.py
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# https://docs.djangoproject.com/en/5.0/topics/i18n/
main

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
codex/enable-django-admin-in-urls.py
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# https://docs.djangoproject.com/en/5.0/howto/static-files/
 main

STATIC_URL = "static/"

# Default primary key field type
codex/enable-django-admin-in-urls.py
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
 main

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
