name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pillow ruff black pytest
      - name: Lint (ruff)
        run: |
          ruff check . || true
      - name: Format check (black)
        run: |
          black --check . || true
      - name: Django checks
        run: |
          python manage.py check
      - name: Migrations dry run
        run: |
          python manage.py makemigrations --check --dry-run
      - name: Unit tests (if any)
        run: |
          pytest -q || true

